version: 2.1

jobs:
  build:
    docker:
      - image: devkitpro/devkitarm:20230526

    steps:
      - checkout
      - run:
          name: install & make
          command: |
            rustup default nightly &&
            cargo install --locked cargo-3ds &&
            make debug

workflows:
  debug_build-workflow:
    jobs:
      - build
