version: 2.1

jobs:
  build:
    docker:
      - image: devkitpro/devkitarm

    steps:
      - checkout
      - run:
          name: make
          command: make debug

workflows:
  debug_build-workflow:
    jobs:
      - build
